function getSingleValue(data){
	var rawVal = ((data.raw & this.bitrange.mask)>>this.bitrange.shift)
	Rmin       = this.valuerange.min
	Rmax       = this.valuerange.max
	Smin       = this.datarange.min
	Smax       = this.datarange.max
	var val    = ((Smax-Smin)/(Rmax-Rmin))*(rawVal-Rmin)+Smin
	return {value:val,type:this.type,unit:this.unit}
}

module.exports = {
//------------------------------------------------------------------------------------------
// temperature sensors a5-2-1 to a5-2-30
//------------------------------------------------------------------------------------------
	"a5-2-1":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-40,
			max:0
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-2":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-30,
			max:10
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-3":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-20,
			max:20
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-4":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-10,
			max:30
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-5":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:0,
			max:40
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-6":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:10,
			max:50
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-7":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:20,
			max:60
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-8":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:30,
			max:70
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-9":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:40,
			max:80
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-a":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:50,
			max:90
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-b":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:60,
			max:100
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-10":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-60,
			max:20
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-11":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-50,
			max:30
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-12":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-40,
			max:40
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-13":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-30,
			max:50
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-14":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-20,
			max:60
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-15":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-10,
			max:70
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-16":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:0,
			max:80
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-17":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:10,
			max:90
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-18":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:20,
			max:100
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-19":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:30,
			max:110
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-1a":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:40,
			max:120
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-1b":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:50,
			max:130
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-20":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:1023,
			max:0
		},
		bitrange:{
			mask:parseInt("111111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-10,
			max:41.2
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-30":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:1023,
			max:0
		},
		bitrange:{
			mask:parseInt("111111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-40,
			max:62.3
		},
		getValue:getSingleValue,
	}
}

