function getSingleValue(data){
	var rawVal = ((data.raw & this.bitrange.mask)>>this.bitrange.shift)
	Rmin       = this.valuerange.min
	Rmax       = this.valuerange.max
	Smin       = this.datarange.min
	Smax       = this.datarange.max
	var val    = ((Smax-Smin)/(Rmax-Rmin))*(rawVal-Rmin)+Smin
	return {value:val,type:this.type,unit:this.unit}
}

function getMultiValues(data){
	var ret=[]
	for(var i=0;i<this.valuerange.min.length;i++){
		switch(this.valuetype[i]){
			case "number":
				var rawVal = ((data.raw & this.bitrange.mask[i])>>>this.bitrange.shift[i])
				Rmin       = this.valuerange.min[i]
				Rmax       = this.valuerange.max[i]
				Smin       = this.datarange.min[i]
				Smax       = this.datarange.max[i]
				var val    = ((Smax-Smin)/(Rmax-Rmin))*(rawVal-Rmin)+Smin
				if(rawVal>this.valuerange.max[i] || rawVal<this.valuerange.min[i]){val="undefined"}
				ret.push({value:val,type:this.type[i],unit:this.unit[i],raw:rawVal})
			break;
			case "enum":
				var rawVal = ((data.raw & this.bitrange.mask[i])>>this.bitrange.shift[i])
				ret.push({value:this.datarange.min[i][rawVal],type:this.type[i],unit:this.unit[i]})
			break;
		}
	}
	return ret
}

module.exports = {
//------------------------------------------------------------------------------------------
// temperature sensors a5-2-1 to a5-2-30
//------------------------------------------------------------------------------------------
	"a5-2-1":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-40,
			max:0
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-2":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-30,
			max:10
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-3":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-20,
			max:20
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-4":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-10,
			max:30
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-5":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:0,
			max:40
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-6":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:10,
			max:50
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-7":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:20,
			max:60
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-8":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:30,
			max:70
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-9":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:40,
			max:80
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-a":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:50,
			max:90
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-b":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:60,
			max:100
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-10":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-60,
			max:20
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-11":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-50,
			max:30
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-12":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-40,
			max:40
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-13":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-30,
			max:50
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-14":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-20,
			max:60
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-15":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-10,
			max:70
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-16":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:0,
			max:80
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-17":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:10,
			max:90
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-18":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:20,
			max:100
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-19":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:30,
			max:110
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-1a":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:40,
			max:120
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-1b":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:255,
			max:0
		},
		bitrange:{
			mask:parseInt("1111111100000000",2),
			shift:8,
		},
		datarange:{
			min:50,
			max:130
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-20":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:1023,
			max:0
		},
		bitrange:{
			mask:parseInt("111111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-10,
			max:41.2
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-2-30":{
		type:"temperature",
		unit:"°C",
		valuerange:{
			min:1023,
			max:0
		},
		bitrange:{
			mask:parseInt("111111111100000000",2),
			shift:8,
		},
		datarange:{
			min:-40,
			max:62.3
		},
		getValue:getSingleValue,
	},
//------------------------------------------------------------------------------------------
	"a5-10-11":{
		valuetype:["number","number","number","enum"],
		type:["SetPoint","humidity","temperature","Day/Night"],
		unit:["","%rF","°C",""],
		valuerange:{
			min:[0,0,0,"enum"],
			max:[255,250,250,"enum"]
		},
		bitrange:{
			mask:[parseInt("11111111000000000000000000000000",2),parseInt("111111110000000000000000",2),parseInt("1111111100000000",2),parseInt("1",2)],
			shift:[24,16,8,0],
		},
		datarange:{
			min:[0,0,0,["Night","Day"]],
			max:[255,100,40]
		},
		getValue:getMultiValues,
	}
}

